### ISSUE TITLE
"Extra Files" allowing you to bypass the payments

### ISSUE THREAD

**Issue by ValentinJesse** [dloa/browser-react#52]
Payments can be bypassed because the "Extra Files" are exposing all of the uploaded files. Happens when people are adding covers/preview images

![chrome_2017-05-17_12-24-13](https://cloud.githubusercontent.com/assets/7979136/26149761/caf5246a-3afb-11e7-8505-f7095fdcddec.png)
____
![2017-05-17_12-24-18](https://cloud.githubusercontent.com/assets/7979136/26149765/cc8b54f2-3afb-11e7-98e3-4abe2669363d.png)

**Comment by OstlerDev** [comment]
This should hopefully be fixed in this commit: ce432f3bac9f106b5e3fab278f9fe917c736b002
